### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by erszcz** [odo/quantile_estimator#2]
@odo @jemc Thanks for your work on this project!

I got here as `quantile_estimator` is a dependency of [`prometheus.erl`](https://github.com/deadtrickster/prometheus.erl). It would be of great help if this library listed the license it's released under or state that it's in the public domain if that's the case. It's relatively easy to add a license file based on templates provided by GitHub, e.g. following the steps from https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/. prometheus.erl itself is released under the MIT License, so using the same one would definitely make life of downstream project maintainers easier 🥺

What do you think?

**Comment by odo** [comment]
Hey Joe,

happy to see that the project is been used!
I just added an MIT license so should be good to go.

Cheers from Berlin,
Florian
