### ISSUE TITLE
Tag and release?

### ISSUE THREAD

**Issue by kivra-pauoli** [odo/quantile_estimator#6]
Hi, @odo.

Would it be possible to Git-tag and GitHub-release `quantile_estimator`?

Cheers.

**Comment by kivra-pauoli** [comment]
@odo, this might also be of interest: https://github.com/deadtrickster/prometheus.erl/issues/163#issuecomment-2122326677 😄

**Comment by kivra-pauoli** [comment]
@odo, anything I can help with to make this move forward?

I think, per https://github.com/deadtrickster/prometheus.erl/issues/163#issuecomment-2122326677, @ikavgo is willing to add you as Hex package maintainer for `quantile estimator` so we can use that not only for Hex but for `prometheus.erl` later (it already pulls from Hex: https://github.com/deadtrickster/prometheus.erl/blob/d1aad4aaebaeecf20e611177ddb287363c726a14/rebar.config#L20)

Thanks.

**Comment by odo** [comment]
Sure, just released the library: https://github.com/odo/quantile_estimator/releases/tag/v1.0.0
Let me know what else I can help with

**Comment by kivra-pauoli** [comment]
Thank you. If you reply in the linked thread, https://github.com/deadtrickster/prometheus.erl/issues/163#issuecomment-2122326677, it's possible you get admin. rights agreed with @ikavgo, on the package, and publish in Hex too, for best compatibility 😄 (otherwise we keep having to forcibly import this one alongside `prometheus.erl` which is what we use primarily). Then a secondary release on the latter (and from now on) would "solve" our issue.

**Comment by kivra-pauoli** [comment]
I can open a separate issue if you prefer to deal with the Hex.pm issue, with all the details I have.

**Comment by odo** [comment]
Yes, a separate issue would make sense.

**Comment by kivra-pauoli** [comment]
Done: https://github.com/odo/quantile_estimator/issues/7. Close'ing... Thanks.
